name: 'franka_moveit_planner'

ros_launch:
  mode: test
  name: ${name}
  wait: 30

  test:
    common: "roslaunch panda_moveit_config move_group.launch fake_execution:=false load_gripper:=true info:=true"

algorithm:
  _target_: pyrobot.algorithms.motion_planning_impl.moveit_planner.MoveitPlanner

robot_labels: ['franka']

conf:
  IK_POSITION_TOLERANCE: 0.005
  IK_ORIENTATION_TOLERANCE: 0.05
