# names of the joints
string[] joint_names

# lower bound on the angular position in radians
float64[] position_lower

# upper bound on the angular position in radians
float64[] position_upper

# symmetric maximum joint velocity in radians/second
float64[] velocity

# symmetric maximum joint acceleration in radians/second^2
float64[] accel

# symmetric maximum joint torque in Newton-meters
float64[] effort
